Votes/urls.py
from django.urls import path
from . import views
 
app_name = 'Votes'
urlpatterns = [
    path('', views.index, name ='index'),
    path('<int:question_id>/', views.details, name ='detail'),
    path('<int:question_id>/results/', views.results, name ='results'),
    path('<int:question_id>/vote/', views.vote, name ='vote'),
]

Voting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('Votes/', include('Votes.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.index, name='index'),
]

Votes/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    

pages/models.py
from django.db import models

# Create your models here.

Votes/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms

from .models import Question, Choice

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def details(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except:
        raise Http404('No such question')
    
    return render(request, 'polls/details.html', {'question':question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question':question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('Votes:results', args=(question.id,)))

pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="stylesheet" href="/static/css/style.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Pollster {% block title %}{% endblock %}</title>
</head>

<body>
	<!--NavBar-->
	{% include 'partials/navbar.html'%}
	<div class="container">
		<div class="row">
			<div class=".col-md-6 m-auto">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>

</html>

templates/details.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<div class="form-check">
		<input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
			value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center mb-3">Poll Questions</h1>
{% if latest_question_list %}
{% for question in latest_question_list %}
<div class="card-mb-3">
	<div class="card-body">
		<p class="lead">{{ question.question_text }}</p>
		<a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
		<a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
	</div>
</div>
{% endfor %}
{% else %}
<p>No polls available</p>
{% endif %}
{% endblock %}

templates/pages/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		body{
			background-image: url("/static/image/mos-design-NinDPAtx0w4-unsplash.jpg");
			background-position: center;
			background-size: cover;
		}
	
	</style>
	<link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
	
	<div class="img">
		{% extends 'base.html' %}
		{% block content %}
		<marquee style="color:rgb(0, 0, 0); font-size: 20px;">
			⚡️Welcome To Polling ⚡️
			  🚀Website Connect
			  To Your First Voting Feature of Tomorrow
			  Today.🚀
			  
		  </marquee>
		<div class="card text-center" style="margin-top: 400px; border-radius:20px;">
			<div class="card-body"  >
				<h1 style="text-align: center;">Welcome To Pooling Website!</h1>
				<p style="margin-left: 100px;">Polling Website. Cast your vote</p>
				<a class="btn btn-dark" href="{% url 'Votes:index' %}">
					View Available Polls</a>
			</div>
		</div>
		{% endblock %}
	</div>
</body>
</html>

templates/partials/navbar.html
<nav class="navbar navbar-dark bg-primary mb-4" style="background-color: black; color: black;">
	<div class="container" >
		<a class="navbar-brand" href="/">Ronak Soni</a>
		<a class="navbar-brand" href="/">Welcome Votes</a>
	</div>
</nav>

templates/polls/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="stylesheet" href="/static/css/style.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
		integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>Pollster {% block title %}{% endblock %}</title>
</head>

<body>
	<!--NavBar-->
	{% include 'partials/navbar.html'%}
	<div class="container">
		<div class="row">
			<div class=".col-md-6 m-auto">
				{% block content %}{% endblock%}
			</div>
		</div>
	</div>
</body>

</html>

templates/polls/details.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'Votes:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'Votes:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<div class="form-check">
		<input type="radio" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"
			value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		.image{
			background-image: url("/static/image/thisisengineering-raeng-uOhBxB23Wao-unsplash.jpg");
			background-position: center;
			background-size: cover;
			height: 730px;
		}
		.containers{
			margin-top:100px;
		}
	</style>
</head>

<body>
	<div class="image">
		
	{% extends 'base.html' %}
	{% block content %}
	
	<div class="containers">
	<h1 class="text-center mb-3">Questions Lists</h1>
	{% if latest_question_list %}
	{% for question in latest_question_list %}
	<div class="card-mb-3">
		<div class="card-body">
			<p class="lead">{{ question.question_text }}</p>
			<a href="{% url 'Votes:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
			<a href="{% url 'Votes:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
		</div>
	</div>
	{% endfor %}
	{% else %}
	<p>No polls available</p>
	{% endif %}
	{% endblock %}
</div>
	</div>
</body>

</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		.img {
			background-image: url("/static/image/kelly-sikkema-xoU52jUVUXA-unsplash.jpg");
			background-position: center;
			background-size: cover;
			height: 730px;
		}

		.list-group-item:first-child {
			background-color: rgb(207, 170, 190);
			border-top-left-radius: 0.25rem;
			border-top-right-radius: 0.25rem;
		}

		.list-group-item+.list-group-item {
			background-color: rgb(221, 216, 223);
			border-top-width: 0;
		}
	</style>
</head>

<body>
	<div class="img">
		{% extends 'base.html' %}
		{% block content %}
		<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

		<ul class="list-group mb-5">
			{% for choice in question.choice_set.all %}
			<li class="list-group-item">
				{{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }}
					vote{{ choice.votes | pluralize }}</span>
			</li>
			{% endfor %}
		</ul>

		<a class="btn btn-secondary" href="{% url 'Votes:index' %}">Back To Polls</a>
		<a class="btn btn-dark" href="{% url 'Votes:detail' question.id %}">Vote again?</a>
		{% endblock %}
	</div>
</body>

</html>

templates/results.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="/static/css/style.css">
	<style>
		.mains{
			background-image: url("/static/image/clay-banks-JU1N79c2i8g-unsplash.jpg");
			background-position: center;
			background-size: cover;
			height: 730px;
		}
	</style>
</head>

<body>
	
	{% extends 'base.html' %}
	{% block content %}
	<div class="mains">
	<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

	<ul class="list-group mb-5">
		{% for choice in question.choice_set.all %}
		<li class="list-group-item">
			{{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }}
				vote{{ choice.votes | pluralize }}</span>
		</li>
		{% endfor %}
	</ul>

	<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
	</div>
</body>

</html>

templates/vote/results.html
{% extends 'base.html' %}
{% block contents %}
<h1 class='mb-5 text-center'> {{ question.question_test }}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class='list-group-item'>
        {{ choice.choice-text }} <span class= 'badge badge-sucess float-right'>
            {{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}

    <a class="btn btn-secondary" href="{{% url 'vote:index' %}}">Back to Voting page</a>
    <a class="btn btn-dark" href="{{% url 'vote:detail' question_id %}}"> Vote Again</a>

{% endblock %}